### ISSUE TITLE
Platform error sensor.moneydashboard - Integration 'moneydashboard' not found.

### ISSUE THREAD

**Issue by J0han3s** [shutupflanders/sensor.moneydashboard#5]
Thank you for very much for creating this integration. I look forward to using it

Hi, does this integration still work?

i get the following error, when a do a config check, before i restart the server.:

`Platform error sensor.moneydashboard - Integration 'moneydashboard' not found.

this is my YAML

sensor:
  - platform: moneydashboard
    email: -gpkf***@gmail.com
    password: pass****rd'

**Comment by shutupflanders** [comment]
Hi,

It's been a while since I've upgraded my HomeAssistant instance as I stayed back after the custom component fiasco - are you installing this via HACS or have you copied the codebase to the specified directory in the readme?

**Comment by J0han3s** [comment]
HI,

Thank you for responding. I am installing this via HACS. I can see the installation has put the folders and files in the custom components folder. However, the issue I mentioned still occurs.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by shutupflanders** [comment]
Hi,

Try remove the above sensor block from your configuration and restart, then re-add it and try a config check again.

Unless you've already tried that - what version of HA and HACS are you using?

**Comment by J0han3s** [comment]
Hi ,

Thanks again for assisting. Yes, I had tried it and tried it again, with no luck. When I removed it, I was able to restart, but could not add it back in. 

`Platform error sensor.moneydashboard - Integration 'moneydashboard' not found.

Home Assistant 2021.7.4

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.0-0.bpo.8-amd64
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4875
Installed Version | 1.15.0
Stage | running
Available Repositories | 940
Installed Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 1
mode | storage

</details>
`

**Comment by shutupflanders** [comment]
I'm still on `core-2020.12.2` so I'll have to try setup a new dev environment and have a look at it at some point.
I'm really busy with work so it might not be for a while I'm afraid.

**Comment by J0han3s** [comment]
Thats fine, thank you.

Please keep me posted if/when you get around to it.

Looking forward to using this integration.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thekitehunter** [comment]
My log showed:
2021-09-03 14:52:09 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'moneydashboard' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details.
Which says:
"_The version key is required from Home Assistant version 2021.6_"

I added the line:   "version": ["21.1.1"], to the manifest.json file and it now appears as an integration
 Hope that helps

**Comment by slunat** [comment]
Just dropped by to say im running into the same issue. Managed to get it to at least detect the integration by make the change to the manifest file as above. Unfortunately, I am still not able to get it working as the plugin won't start. My logs show the below:

`2021-12-05 21:13:52 ERROR (SyncWorker_5) [root] [HTTP Error]: Failed to login (400 Client Error: Bad Request for url: https://my.moneydashboard.com/landing/login)
2021-12-05 21:13:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up moneydashboard platform for sensor
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/moneydashboard/moneydashboard.py", line 76, in login
response.raise_for_status()
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://my.moneydashboard.com/landing/login
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/moneydashboard/sensor.py", line 60, in update
data = json.loads(self._md.get_balances())
File "/usr/local/lib/python3.9/site-packages/moneydashboard/moneydashboard.py", line 135, in get_balances
accounts = self.get_accounts()
File "/usr/local/lib/python3.9/site-packages/moneydashboard/moneydashboard.py", line 95, in get_accounts
self.login()
File "/usr/local/lib/python3.9/site-packages/moneydashboard/moneydashboard.py", line 79, in login
raise LoginFailedException
moneydashboard.moneydashboard.LoginFailedException
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/moneydashboard/sensor.py", line 41, in setup_platform
add_entities([MoneyDashboardBalances(md=md, unit_of_measurement="GBP")])
File "/config/custom_components/moneydashboard/sensor.py", line 54, in __init__
self.update()
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/moneydashboard/sensor.py", line 64, in update
except GetAccountsListFailedException:
NameError: name 'GetAccountsListFailedException' is not defined`

My login details are definitely correct as I have signed in manually with the same details as what I have in my config file, so there is an issue somewhere else.

**Comment by thekitehunter** [comment]
As well as the version number being missing, the log in page has changed, per the error message:
Bad Request for url: https://my.moneydashboard.com/landing/login
its now:
https://my.moneydashboard.com/?signin=true ... and the login is probably different, so this integration is now dead and needs removing
